services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:latest
    container_name: test-postgres-container
    restart: always
    ports:
      - "5430:5430"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

volumes:
  postgres_data:
