name: Build and Test on SonarCloud

on:
  push:
    branches: ["dev", "master", "newbranch-testing"]
  pull_request:
    branches: ["dev", "master"]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    services:
      test-postgres-container:
        image: postgres:latest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5431:5431
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install tox
          
      - name: Check postgres connection
        run: |
            until pg_isready -h localhost -p 5431 -U test_user; do
             >&2 echo "Postgres is unavailable - sleeping"
              sleep 1
            done
            >&2 echo "Postgres is up - executing command"

      - name: Run tox
        run: tox -e py

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
